version: "3.8"

services:
  app:
    image: music-app-backend:v1
    ports:
      - "4000:4000"
    restart: unless-stopped
  mongodb:
    image: mongo:4.4.4-bionic
    ports:
      - 27018:27017
  mongo-seed:
    image: mongo:4.4.4-bionic
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/import.sh
