version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace/music-app-backend
    ports:
      - 4000:4000
    restart: always
    depends_on:
      - mongodb
  mongodb:
    hostname: mongodb
    image: mongo:4.4.4-bionic
    restart: always
    container_name: mongodb-music
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
